# Gradle properties
org.gradle.jvmargs=-Xmx1G

# Build configuration
version=1.0.0
group=dev.azuuure
archive_base_name=better-player-list

# Fabric-related stuff. See https://fabricmc.net/develop/
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.2
fabric_version=0.139.4+1.21.11

# Other dependencies
modmenu_version=17.0.0-alpha.1
devauth_version=1.2.2
