# Gradle properties
org.gradle.jvmargs=-Xmx1G

# Build configuration
version=1.0.1-SNAPSHOT
group=dev.azuuure
archive_base_name=better-player-list

# Fabric-related stuff. See https://fabricmc.net/develop/
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.18.2
fabric_version=0.119.4+1.21.4

# Other dependencies
modmenu_version=13.0.2
devauth_version=1.2.2
