# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Build configuration
version=1.2.0-beta.2
group=dev.azuuure.playerlist
license=MIT
mod_id=betterplayerlist
mod_name=BetterPlayerList
mod_description=Various Minecraft player list enhancements, such as numeric ping instead of connection bars.
archive_base_name=better-player-list