modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="https://github.com/azurejelly/better-player-list/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/azurejelly/better-player-list"
logoFile="icon.png"
authors="azurejelly"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
